variable "vm-name" {}
variable "resource_group_name" {}
variable "location" {}
variable "admin_username" {}
variable "admin_password" {}
variable "network_interface_ids" {}
variable "image-publisher" {}
variable "image-offer" {}
variable "image-sku" {}  
